chore: add missing extensions to have e2e tests work on node 22
Without these Node would complain with the following error:

Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/dev/gn-ui/tools/e2e/settings' imported from /dev/gn-ui/tools/e2e/plugins.js

see https://nodejs.org/api/esm.html#esm_mandatory_file_extensions